// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frigg.proto

/*
Package friggpb is a generated protocol buffer package.

It is generated from these files:
	frigg.proto

It has these top-level messages:
	TraceByIDRequest
	TraceByIDResponse
	Trace
	PushRequest
	PushResponse
*/
package friggpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import opentelemetry_proto_collector_trace_v1 "github.com/open-telemetry/opentelemetry-proto/gen/go/collector/traces/v1"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TraceByIDRequest struct {
	TraceID []byte `protobuf:"bytes,1,opt,name=traceID,proto3" json:"traceID,omitempty"`
}

func (m *TraceByIDRequest) Reset()                    { *m = TraceByIDRequest{} }
func (m *TraceByIDRequest) String() string            { return proto.CompactTextString(m) }
func (*TraceByIDRequest) ProtoMessage()               {}
func (*TraceByIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TraceByIDRequest) GetTraceID() []byte {
	if m != nil {
		return m.TraceID
	}
	return nil
}

type TraceByIDResponse struct {
	Trace *Trace `protobuf:"bytes,1,opt,name=trace" json:"trace,omitempty"`
}

func (m *TraceByIDResponse) Reset()                    { *m = TraceByIDResponse{} }
func (m *TraceByIDResponse) String() string            { return proto.CompactTextString(m) }
func (*TraceByIDResponse) ProtoMessage()               {}
func (*TraceByIDResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TraceByIDResponse) GetTrace() *Trace {
	if m != nil {
		return m.Trace
	}
	return nil
}

type Trace struct {
	Batches []*opentelemetry_proto_collector_trace_v1.ResourceSpans `protobuf:"bytes,1,rep,name=batches" json:"batches,omitempty"`
}

func (m *Trace) Reset()                    { *m = Trace{} }
func (m *Trace) String() string            { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()               {}
func (*Trace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Trace) GetBatches() []*opentelemetry_proto_collector_trace_v1.ResourceSpans {
	if m != nil {
		return m.Batches
	}
	return nil
}

type PushRequest struct {
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceSpans []byte `protobuf:"bytes,2,opt,name=resourceSpans,proto3" json:"resourceSpans,omitempty"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PushRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PushRequest) GetResourceSpans() []byte {
	if m != nil {
		return m.ResourceSpans
	}
	return nil
}

type PushResponse struct {
}

func (m *PushResponse) Reset()                    { *m = PushResponse{} }
func (m *PushResponse) String() string            { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()               {}
func (*PushResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*TraceByIDRequest)(nil), "friggpb.TraceByIDRequest")
	proto.RegisterType((*TraceByIDResponse)(nil), "friggpb.TraceByIDResponse")
	proto.RegisterType((*Trace)(nil), "friggpb.Trace")
	proto.RegisterType((*PushRequest)(nil), "friggpb.PushRequest")
	proto.RegisterType((*PushResponse)(nil), "friggpb.PushResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Pusher service

type PusherClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
}

type pusherClient struct {
	cc *grpc.ClientConn
}

func NewPusherClient(cc *grpc.ClientConn) PusherClient {
	return &pusherClient{cc}
}

func (c *pusherClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := grpc.Invoke(ctx, "/friggpb.Pusher/Push", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pusher service

type PusherServer interface {
	Push(context.Context, *PushRequest) (*PushResponse, error)
}

func RegisterPusherServer(s *grpc.Server, srv PusherServer) {
	s.RegisterService(&_Pusher_serviceDesc, srv)
}

func _Pusher_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PusherServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/friggpb.Pusher/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PusherServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pusher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "friggpb.Pusher",
	HandlerType: (*PusherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Pusher_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frigg.proto",
}

// Client API for Querier service

type QuerierClient interface {
	FindTraceByID(ctx context.Context, in *TraceByIDRequest, opts ...grpc.CallOption) (*TraceByIDResponse, error)
}

type querierClient struct {
	cc *grpc.ClientConn
}

func NewQuerierClient(cc *grpc.ClientConn) QuerierClient {
	return &querierClient{cc}
}

func (c *querierClient) FindTraceByID(ctx context.Context, in *TraceByIDRequest, opts ...grpc.CallOption) (*TraceByIDResponse, error) {
	out := new(TraceByIDResponse)
	err := grpc.Invoke(ctx, "/friggpb.Querier/FindTraceByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Querier service

type QuerierServer interface {
	FindTraceByID(context.Context, *TraceByIDRequest) (*TraceByIDResponse, error)
}

func RegisterQuerierServer(s *grpc.Server, srv QuerierServer) {
	s.RegisterService(&_Querier_serviceDesc, srv)
}

func _Querier_FindTraceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).FindTraceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/friggpb.Querier/FindTraceByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).FindTraceByID(ctx, req.(*TraceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Querier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "friggpb.Querier",
	HandlerType: (*QuerierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindTraceByID",
			Handler:    _Querier_FindTraceByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frigg.proto",
}

func init() { proto.RegisterFile("frigg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x41, 0x4f, 0xf2, 0x40,
	0x14, 0xfc, 0xe0, 0x13, 0x9a, 0xbc, 0x02, 0xd1, 0x8d, 0x26, 0xb5, 0x27, 0xb2, 0xe1, 0xc0, 0xc1,
	0x6c, 0x43, 0x0d, 0x07, 0xbd, 0x98, 0x28, 0x31, 0x72, 0x52, 0x8b, 0x07, 0x6f, 0x06, 0x96, 0x27,
	0x6c, 0x82, 0xdd, 0xba, 0xbb, 0x25, 0xe1, 0xdf, 0x9b, 0xee, 0xd2, 0xa6, 0x35, 0xde, 0x76, 0xde,
	0xcc, 0x9b, 0x9d, 0x37, 0xe0, 0x7f, 0x2a, 0xb1, 0xd9, 0xb0, 0x4c, 0x49, 0x23, 0x89, 0x67, 0x41,
	0xb6, 0x0a, 0x6f, 0x65, 0x86, 0xa9, 0xc1, 0x1d, 0x7e, 0xa1, 0x51, 0x87, 0xc8, 0xb2, 0x11, 0x97,
	0xbb, 0x1d, 0x72, 0x23, 0x55, 0x64, 0xd4, 0x92, 0x63, 0xb4, 0x9f, 0xb8, 0xc7, 0x87, 0x46, 0xb5,
	0x17, 0x1c, 0x9d, 0x09, 0xbd, 0x82, 0xd3, 0xb7, 0x62, 0x7c, 0x7f, 0x98, 0xcf, 0x12, 0xfc, 0xce,
	0x51, 0x1b, 0x12, 0x80, 0x67, 0xa5, 0xf3, 0x59, 0xd0, 0x1a, 0xb6, 0xc6, 0xbd, 0xa4, 0x84, 0xf4,
	0x06, 0xce, 0x6a, 0x6a, 0x9d, 0xc9, 0x54, 0x23, 0x19, 0x41, 0xc7, 0xf2, 0x56, 0xec, 0xc7, 0x03,
	0x76, 0xcc, 0xc5, 0xac, 0x34, 0x71, 0x24, 0x7d, 0x87, 0x8e, 0xc5, 0xe4, 0x19, 0xbc, 0xd5, 0xd2,
	0xf0, 0x2d, 0xea, 0xa0, 0x35, 0xfc, 0x3f, 0xf6, 0xe3, 0x29, 0x6b, 0xe4, 0x77, 0xc1, 0x58, 0x95,
	0x9f, 0xd9, 0x7d, 0xb6, 0x9f, 0xb0, 0x04, 0xb5, 0xcc, 0x15, 0xc7, 0x45, 0xb6, 0x4c, 0x75, 0x52,
	0xba, 0xd0, 0x07, 0xf0, 0x5f, 0x72, 0xbd, 0x2d, 0xd3, 0x0f, 0xa0, 0x2d, 0xd6, 0xc7, 0xe0, 0x6d,
	0xb1, 0x26, 0x23, 0xe8, 0xab, 0xfa, 0x62, 0xd0, 0xb6, 0x54, 0x73, 0x48, 0x07, 0xd0, 0x73, 0x26,
	0xee, 0xa8, 0xf8, 0x0e, 0xba, 0x05, 0x46, 0x45, 0xa6, 0x70, 0x52, 0xbc, 0xc8, 0x79, 0x75, 0x57,
	0xed, 0xb7, 0xf0, 0xe2, 0xd7, 0xd4, 0xad, 0xd3, 0x7f, 0xf1, 0x02, 0xbc, 0xd7, 0x1c, 0x95, 0x40,
	0x45, 0x9e, 0xa0, 0xff, 0x28, 0xd2, 0x75, 0xd5, 0x1c, 0xb9, 0x6c, 0x56, 0x54, 0xeb, 0x3e, 0x0c,
	0xff, 0xa2, 0x4a, 0xd3, 0x55, 0xd7, 0x76, 0x73, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x36, 0x06,
	0x16, 0x4e, 0x08, 0x02, 0x00, 0x00,
}
