apiVersion: v2
name: tempo-single-binary
description: Grafana Tempo Single Binary Mode
type: application
version: 0.1.1
appVersion: v0.2.0
engine: gotpl
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/tempo/master/docs/tempo/website/logo_and_name.png
sources:
  - https://github.com/grafana/tempo
maintainers:
  - name: Joe Elliott
    email: number101010@gmail.com
  - name: Swartz K
    email: 9215868@gmail.com