# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

replicas: 1
tempo:
  repository: grafana/tempo
  tag: latest
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

  updateStrategy: RollingUpdate
  resources: {}
  #  limits:
  #    cpu: 1000m
  #    memory: 4Gi
  #  requests:
  #    cpu: 2000m
  #    memory: 6Gi

  memBallastSizeMbs: 1024
  authEnabled: false
  ingester:
  retention: 24h
  server:
    httpListenPort: 3100
  # tempo storage backend
  # refer https://github.com/grafana/tempo/tree/master/docs/tempo/website/configuration
  ## Use s3 for example
  # backend: s3                                         # store traces in s3
  #  s3:
  #    bucket: tempo                                   # store traces in this bucket
  #    endpoint: s3.dualstack.us-east-2.amazonaws.com  # api endpoint
  #    access_key: ...                                 # optional. access key when using static credentials.
  #    secret_key: ...                                 # optional. secret key when using static credentials.
  #    insecure: false                                 # optional. enable if endpoint is http
  ## end
  storage: |
    backend: local
      local:
        path: /tmp/tempo/traces
      wal:
        path: /var/tempo/wal
  # this configuration will listen on all ports and protocols that tempo is capable of.
  # the receives all come from the OpenTelemetry collector.  more configuration information can
  # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver
  receivers:
    jaeger:
      protocols:
        thrift_http: null

tempoQuery:
  repository: rafana/tempo-query
  tag: latest
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

service:
  type: ClusterIP
  annotations: {}
  labels: {}

persistence:
  enabled: false
  # storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  size: 10Gi

# -- Environment variables to add
extraEnv: []
# -- Environment variables from secrets or configmaps to add
extraEnvFrom: []
# -- Volume mounts to add
extraVolumeMounts: []
# - name: extra-volume
#   mountPath: /mnt/volume
#   readOnly: true
#   existingClaim: volume-claim

# -- Volumes to add
extraVolumes: []

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
