apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  ports:
  - name: querier-prom-metrics
    port: 3100
    targetPort: 3100
  - name: tempo-query-jaeger-ui
    port: 16686
    targetPort: 16686
  selector:
    {{- include "tempo.querier.selectorLabels" . | nindent 4 }}