apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.fullname" . }}-memcached
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    targetPort: 9150
  selector:
    {{- include "tempo.memcached.selectorLabels" . | nindent 4 }}